apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: payment-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3004
          hostPort: 3004
        envFrom:
        - secretRef:
            name: simtech-secrets
        # securityContext:
        #   runAsUser: 1000
        #   runAsGroup: 3000
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     add: ["NET_BIND_SERVICE"]
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 3004
  type: ClusterIP
