apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service
        image: order-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3003
          hostPort: 3003
        envFrom:
        - secretRef:
            name: simtech-secrets
        # securityContext:
        #   runAsUser: 1000
        #   runAsGroup: 3000
        #   allowPrivilegeEscalation: false
        #   capabilities:
        #     add: ["NET_BIND_SERVICE"]
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
spec:
  selector:
    app: order-service
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 3003
  type: ClusterIP
